matrix:
    include:
      - language: python
        python:
            - '2.7'
            - '3.6'
        install:
            - pip install -r requirements.txt
            - python setup.py install
        script:
            - pytest
        cache: pip
      - language: cpp
        before_install:
            - git submodule update --init
            - sudo apt-get update
            - sudo apt-get install -y build-essential autoconf libtool pkg-config
            - | 
                if [[ ! -f ${TRAVIS_BUILD_DIR}/install/bin/protoc ]]; then
                  git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
                  cd grpc
                  git submodule update --init
                  mkdir -p build && cd build
                  cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install && make -j4 all install
                  mkdir -p ${TRAVIS_BUILD_DIR}/cpp/bmi-c/build && cd ${TRAVIS_BUILD_DIR}/cpp/bmi-c/build
                  cmake .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install && make all install
                else
                  echo "using cached builds of protobuf, grpc and bmi-c..."
                fi
        script:
            - export PATH=${PATH}:${TRAVIS_BUILD_DIR}/install/bin
            - export LD_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib
            - mkdir -p ${TRAVIS_BUILD_DIR}/cpp/build && cd ${TRAVIS_BUILD_DIR}/cpp/build
            - cmake .. -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib -DCMAKE_INCLUDE_PATH=${TRAVIS_BUILD_DIR}/install/include -DCMAKE_PATH=${TRAVIS_BUILD_DIR}/install/bin
            - cmake --build .
            - ctest
        cache:
            directories:
                - ${TRAVIS_BUILD_DIR}/install
