matrix:
    include:
      - language: python
        python:
            - '2.7'
            - '3.6'
        install:
            - pip install -r requirements.txt
            - python setup.py install
        script:
            - pytest
        cache: pip
      - language: cpp
        before_install:
            - git submodule update --init
            - sudo apt-get update
            - sudo apt-get install -y build-essential autoconf libtool pkg-config
            - [ -d grpc ] || git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
            - cd grpc
            - git submodule update --init
            - sudo make install
            - cd third_party/protobuf
            - sudo make install
            - mkdir -p ${TRAVIS_BUILD_DIR}/cpp/bmi-c/build && cd ${TRAVIS_BUILD_DIR}/cpp/bmi-c/build
            - cmake ..
            - sudo make install
        script:
            - mkdir -p ${TRAVIS_BUILD_DIR}/cpp/build && cd ${TRAVIS_BUILD_DIR}/cpp/build
            - cmake ..
            - cmake --build .
            - ctest
        cache:
            directories:
                - grpc
