matrix:
    include:
      - language: python
        python:
            - '2.7'
            - '3.6'
        install:
            - pip install -r requirements.txt
            - python setup.py install
        script:
            - pytest
        cache: pip
      - language: cpp
        before_install:
            - git submodule update --init
            - sudo apt-get update
            - sudo apt-get install -y build-essential autoconf libtool pkg-config openssl
            - | 
                if [[ ! -f ${TRAVIS_BUILD_DIR}/install/bin/protoc ]]; then
                  git clone https://github.com/grpc/grpc
                  cd grpc
                  git submodule update --init --recursive
                  # Install c-ares
                  cd third_party/cares/cares
                  git fetch origin
                  git checkout cares-1_13_0
                  mkdir -p build && cd build
                  cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DCMAKE_BUILD_TYPE=Release ..
                  make -j4 install
                  cd ${TRAVIS_BUILD_DIR}/grpc
                  rm -rf third_party/cares/cares  # wipe out to prevent influencing the grpc build
                  # Install zlib
                  cd third_party/zlib
                  mkdir -p build && cd build
                  cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DCMAKE_BUILD_TYPE=Release ..
                  make -j4 install
                  cd ${TRAVIS_BUILD_DIR}/grpc
                  rm -rf third_party/zlib  # wipe out to prevent influencing the grpc build
                  # Install boringssl
                  cd third_party/boringssl
                  mkdir -p build && cd build
                  cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DCMAKE_BUILD_TYPE=Release ..
                  make -j4
                  cd ${TRAVIS_BUILD_DIR}/grpc
                  # Install protobuf
                  cd third_party/protobuf/cmake
                  mkdir -p build && cd build
                  cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release ..
                  make -j4 install
                  cd ${TRAVIS_BUILD_DIR}/grpc
                  rm -rf third_party/protobuf  # wipe out to prevent influencing the grpc build
                  # Install gRPC
                  mkdir -p build && cd build
                  cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DCMAKE_BUILD_TYPE=Release ..
                  make -j4 install
                  cd ${TRAVIS_BUILD_DIR}
                else
                  echo "using cached builds of protobuf, grpc and bmi-c..."
                fi
                echo "Installed programs are $(ls ${TRAVIS_BUILD_DIR}/install/bin)"
                echo "Installed libraries are $(ls ${TRAVIS_BUILD_DIR}/install/lib)"
        script:
            - mkdir -p ${TRAVIS_BUILD_DIR}/cpp/build && cd ${TRAVIS_BUILD_DIR}/cpp/build
            - export PATH=${PATH}:${TRAVIS_BUILD_DIR}/install/bin
            - cmake .. -DCMAKE_LIBRARY_PATH=${TRAVIS_BUILD_DIR}/install/lib -DCMAKE_INCLUDE_PATH=${TRAVIS_BUILD_DIR}/install/include -DCMAKE_PATH=${TRAVIS_BUILD_DIR}/install/bin
            - cmake --build .
            - ctest
        cache:
            directories:
                - ${TRAVIS_BUILD_DIR}/install
