matrix:
    include:
      - language: python
        python:
            - '2.7'
            - '3.6'
        install:
            - pip install -r requirements.txt
            - python setup.py install
        script:
            - pytest
        cache:
            directories:
                - $HOME/cache/pip
      - language: c++
        build:
            - mkdir -p cpp/build
            - cd cpp/build
            - cmake ..
            - make
        script:
            - ctest
