# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py install
    - name: Cache Singularity
      id: cache-singularity
      uses: actions/cache@v2
      with:
        path: /usr/local/bin/singularity
        key: singularity
    - name: Install Singularity
      if: steps.cache-singularity.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev libseccomp-dev pkg-config squashfs-tools
        wget -O /tmp/go1.12.linux-amd64.tar.gz https://dl.google.com/go/go1.12.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go1.12.linux-amd64.tar.gz
        export GOPATH=~/go
        export PATH=$PATH:/usr/local/go/bin
        mkdir -p ~/go/src/github.com/sylabs
        cd ~/go/src/github.com/sylabs && \
        git clone https://github.com/sylabs/singularity.git && \
        cd singularity
        git checkout v3.1.0
        ./mconfig && \
        cd ./builddir && \
        make && \
        sudo make install
        cd ${GITHUB_WORKSPACE}
    - name: Pull Docker image
      run: docker pull ewatercycle/walrus-grpc4bmi:v0.3.1
    - name: Cache Singularity image
      id: cache-singularity-image
      uses: actions/cache@v2
      with:
        path: ~/.singularity
        key: singularity-image
    - name: Pull Singularity image
      if: steps.cache-singularity-image.outputs.cache-hit != 'true'
      run: singularity pull docker://ewatercycle/walrus-grpc4bmi:v0.3.1
    - name: Test with pytest
      run: pytest --cov=grpc4bmi --cov-report xml
    - name: SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build dir
        run: mkdir -p cpp/build
      - name: configure
        run: cmake ..
        working-directory: cpp/build
      - name: make
        run: make VERBOSE=1
        working-directory: cpp/build
      - name: ctest
        run: ctest -V
        working-directory: cpp/build
